services:
  pgstac:
    container_name: pgstac
    image: ghcr.io/stac-utils/pgstac:v0.9.1
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pgstac
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=pgstac
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "pgstac"]
      interval: 1s
      timeout: 20s
      retries: 20
  tistac-pgstac:
    container_name: tistac-pgstac
    build: .
    depends_on:
      pgstac:
        condition: service_healthy