[project]
name = "tistac"
version = "0.1.0"
description = "A small multi-backend STAC API server built on FastAPI."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "pgstacrs>=0.1.0",
    "pydantic>=2.10.4",
    "pydantic-settings>=2.7.1",
    "stacrs>=0.3.0",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "psycopg[pool]>=3.2.3",
    "pypgstac>=0.9.2",
    "pystac>=1.11.0",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.1",
    "pytest-postgresql>=6.1.1",
    "ruff>=0.8.5",
]

[tool.mypy]
strict = true
files = ["**/*.py"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
filterwarnings = [
    "error",
    'ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version.:DeprecationWarning',
]

[tool.ruff.lint]
select = ["E", "F", "I"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
