name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Install postgis
        run: sudo apt-get install postgis
      - name: Install
        run: scripts/install --dev
      - name: Copy env file
        run: cp .env.local .env
      - name: Lint
        run: scripts/lint
      - name: Test
        run: scripts/test
